USE [master]
GO

/****** Object:  Database [Formula1Database]    Script Date: 2/17/2020 1:47:41 PM ******/
CREATE DATABASE [Formula1Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Formula1Database', FILENAME = N'E:\Database\MSSQL12.MSSQLSERVER\MSSQL\DATA\Formula1Database.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Formula1Database_log', FILENAME = N'E:\Database\MSSQL12.MSSQLSERVER\MSSQL\DATA\Formula1Database_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Formula1Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Formula1Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Formula1Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Formula1Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Formula1Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Formula1Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [Formula1Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Formula1Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Formula1Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Formula1Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Formula1Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Formula1Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Formula1Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Formula1Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Formula1Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Formula1Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Formula1Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Formula1Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Formula1Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Formula1Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Formula1Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Formula1Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Formula1Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Formula1Database] SET RECOVERY FULL 
GO

ALTER DATABASE [Formula1Database] SET  MULTI_USER 
GO

ALTER DATABASE [Formula1Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Formula1Database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Formula1Database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Formula1Database] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Formula1Database] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Formula1Database] SET  READ_WRITE 
GO


